name: 'Check Logs'
description: 'Checks GitHub workflows for errors or failures and retrieves logs'
inputs:
  gh_token:
    description: 'GitHub Token'
    required: true
  workflows:
    description: 'Workflow name(s) to check. This input is dynamic and filters will be applied in the script.'
    required: false
    default: ''
outputs:
  workflowRunMessage:
    description: 'Message summarizing the workflow run and its errors'
    value: ${{ steps.check_logs.outputs.workflowRunMessage }}
  workflowRunName:
    description: 'Name of the workflow run'
    value: ${{ steps.check_logs.outputs.workflowRunName }}
  workflowRunId:
    description: 'ID of the workflow run'
    value: ${{ steps.check_logs.outputs.workflowRunId }}
runs:
  using: 'composite'
  steps:
    - name: 'Check Workflow Logs'
      id: check_logs
      shell: pwsh
      run: |
        ${{ github.action_path }}/CheckLogs.ps1 -GH_TOKEN ${{ inputs.gh_token }} -WORKFLOWS ${{ inputs.workflows }}
